# Generated by Django 4.2.3 on 2023-07-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotivationAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationquote',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='motivationquote',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
