# Generated by Django 4.2.3 on 2023-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotivationAPI', '0002_alter_motivationquote_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivationquote',
            old_name='quote_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='motivationquote',
            old_name='text',
            new_name='quote',
        ),
        migrations.AlterField(
            model_name='motivationquote',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
